const items  = [
    {name: 'iphone', isWaste: true},
    {name: 'android', isWaste: false},
    {name: 'minecraft', isWaste: false},
    {name: 'air', isWaste: 'free'},
    {name: 'https', isWaste: 'custom', custom: 'depends', explanation: 'https is not a waste of money if you get it free (cloudflare)'},
    {name: 'this website', isWaste: 'custom', custom: 'how dare you check if this website is a waste of money!! its free how could it possibly be???'},
    {name: 'optifine', isWaste: 'free'},
    {name: 'optifine cape', isWaste: false},
    {name: 'samsung', isWaste: true},
    {name: 'google', isWaste: 'free'},
    {name: 'minecraft bedrock', isWaste: true},
    {name: 'fortnite', isWaste: 'free', explanation: 'but... this <i>is</i> fortnite soooo.... maybe thats not so true'},
    {name: 'money', isWaste: true},
    {name: 'netflix', isWaste: true},
    {name: 'hulu', isWaste: true},
    {name: 'youtube red', isWaste: true},
    {name: 'humble bundle', isWaste: true},
    {name: 'pizza', isWaste: 'custom', custom: 'never', explanation: 'unless it is a <a href="https://i.pinimg.com/originals/3a/be/70/3abe70be046eed475708ee9b0dd21179.jpg">golden pizza</a>'},
    {name: 'testing', isWaste: true, explanation: 'testing is a waste of time and time is money.'},
    {name: 'terraria', isWaste: false, explanation: 'its kinda like minecraft and minecraft is good so no not a waste'},
    {name: 'faithful', isWaste: 'custom', custom: 'depends'},
    {name: 'css', isWaste: 'true', explanation: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'},
    {name: 'water', isWaste: 'custom', custom: 'depends', explanation: 'it really depends on a lot of things'},
    {name: 'toilet paper', isWaste: true, explanation: 'welcome to 2020'},
    {name: 'i', isWaste: true},
    {name: 'my life', isWaste: true},
    {name: 'pain', isWaste: 'custom', custom: 'depends', explanation: 'what kind of pain are you talking about? bread is not a waste of money'},
    {name: 'infinite pain', isWaste: 'free', explanation: 'even though this is free i\'d say its still a waste of free'},
    {name: 'video games', isWaste: 'custom', custom: 'depends', explanation: 'video games is too general i need more than just video games how am i supposed to tell you if all video games are a waste of money?? some are even free so i dont understand what is your problem???'},
    {name: 'minecraft dungeons', isWaste: true},
    {name: 'internet', isWaste: true},
    {name: 'seus ptgi', isWaste: false},
    {name: 'apple pro stand', isWaste: true, explanation: 'A MONITOR STAND FOR 999$?!? ARE YOU FOR REAL, IT DEFINITELY IS A WASTE OF MONEY REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE'},
    {name: 'microtransactions in mobile games', isWaste: true},
    {name: 'minecraft 3ds', isWaste: true},
    {name: 'drugs', isWaste: 'custom', custom: 'depends', explanation: 'im not qualified to tell this to you speak to your doctor or something'}, 
    {name: 'bugle', isWaste: false}, 
    {name: 'band', isWaste: false}, 
    {name: 'food', isWaste: false}, 
    {name: 'chair', isWaste: false}, 
    {name: 'bed', isWaste: false}, 
    {name: 'school', isWaste: 'depends', explanation: 'public school is free and stuff but college is probably a waste of money unless you need a college education for a certain job or something so basically its up to you to decide'}, 
    {name: 'youtube shorts', isWaste: true},
    {name: 'life', isWaste: 'custom', custom: 'depends', explanation: 'If you mean your life, totally, but life in general ... well, I guess, living stuff created money and also ways to waste it, so ... kinda ...'},
    {name: 'github', isWaste: 'free'},
    {name: 'super duolingo', isWaste: true},
    {name: 'discord nitro', isWaste: true},
    {name: 'website builder', isWaste: true},
    {name: 'salvation', isWaste: 'free'},
    {name: '2020 intel macbook air', isWaste: true},
    {name: 'lawsuit', isWaste: 'custom', custom: 'depends', explanation: 'if you\'re the one suing, then probably. unless you win.'},
    {name: 'skibidi toilet fortnite skins', isWaste: true},
    {name: 'reading', isWaste: 'custom', custom: 'not a waste of money. might be a waste of time if the reading isn\'t beneficial to you though.'},
    {name: 'wii', isWaste: false},
    {name: 'wii u', isWaste: true},
    {name: 'fortnite for nintendo switch', isWaste: 'custom', custom: 'fortnite is free but playing it on a nintendo switch is a bad move'},
    {name: 'fortnite crew', isWaste: false},
    {name: 'fortnite', isWaste: 'free'},
    {name: 'nesquik', isWaste: false},
    {name: 'banana bread', isWaste: false},
    {name: 'ps5', isWaste: true},
    {name: 'xbox one', isWaste: true},
    {name: 'xbox series s', isWaste: false},
    {name: 'xbox series x', isWaste: true},
    {name: 'custom built gaming pc', isWaste: false},
    {name: 'bing', isWaste: 'free', explanation: 'it is free to use and also it gives out gift cards so that\'s cool, but otherwise yes do not give bing money'},
    {name: 'nitro basic', isWaste: true, explanation: 'more of a waste than regular discord nitro because you\'re paying $3 for nothing????'},
    {name: 'pc', isWaste: false},
    {name: 'ps4', isWaste: true},
    {name: 'nintendo switch', isWaste: true},
    {name: 'nintendo switch lite', isWaste: true},
    {name: 'github pro', isWaste: 'custom', custom: 'if you\'re a student you can probably get github pro for free. otherwise if you\'re a professional it could not be a waste of money, but if you buy it and do not use it then it is a waste of money.'},
    {name: 'calculus', isWaste: true},
    {name: 'algebra', isWaste: true},
    {name: 'wasteof', isWaste: false},
    {name: 'honey', isWaste: true},
    {name: 'chatgpt pro', isWaste: true},
    {name: 'google gemini advanced', isWaste: true},
    {name: 'ai', isWaste: true},
    {name: 'x premium', isWaste: true},
    {name: 'elon musk mars spaceship', isWaste: true}
];
